# Generated by Django 5.1.1 on 2024-09-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
